spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: afc542d6ead06a
    password: 0a526cffd0bf76
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false