### GET all users
GET http://localhost:8080/users

###

### CREATE valid user
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Yash",
  "email": "yash@gmail.com"
}

###

### TEST validation - empty name + wrong email
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "",
  "email": "wrong-email"
}

###

### UPDATE user id=4
PUT http://localhost:8080/users/4
Content-Type: application/json

{
  "name": "Updated",
  "email": "updated@gmail.com"
}

###

### DELETE user id=4
DELETE http://localhost:8080/users/4